name: CD Terraform Pipeline 

on:
  push:
    branches:
      - master
  workflow_dispatch:
    inputs:
      runApply:
        description: 'Run Terraform Apply? (true/false)' 
        required: true
        default: 'false'


jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1

    - name: Terraform Init
      run: |
        cd terraform
        terraform init -backend-config ./environments/backend.tfvars

    - name: Terraform Validate
      run: |
        cd terraform
        terraform validate

    - name: Terraform Plan
      run: |
        cd terraform
        terraform plan -out planfile.tfplan -var-file ./environments/terraform.tfvars.json

    - name: Terraform Apply
      run: |
        cd terraform
        terraform apply planfile.tfplan -auto-approve
      if: github.event.inputs.runApply == 'true'

env:
  ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}  
  ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}  
  ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}  
  ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}  